### ISSUE TITLE
Support for self signed certs on ES

### ISSUE THREAD

**Issue by twigley** [moshe/elasticsearch-comrade#212]
When using self signed certs on elasticsearch it doesn't seem possible to disable the verification of the certs.

Using a **config** like this:

```
{
    "params":  {
        "hosts": ["localhost"],
        "http_auth": ["elastic", "password"],
        "scheme": "https",
        "verify_certs": "False",
        "port": 9200
    }
}
```

**Logs:**

```

[2019-11-07 10:05:59 +0000] [1] [ERROR] ConnectionError() caused by: ServerDisconnectedError()

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/elasticsearch_async/connection.py", line 98, in perform_request
    response = yield from self.session.request(method, url, data=body, headers=headers)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sanic/app.py", line 942, in handle_request
    response = await response
  File "/app/blueprints/cluster.py", line 36, in get_cluster_info
    await client.ping()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/elasticsearch_async/transport.py", line 150, in main_loop
    method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/elasticsearch_async/connection.py", line 111, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError() caused by: ServerDisconnectedError()
```

To verify the connection can work I can exec into the container e.g
`docker exec -it elastic_noether /bin/sh`
and then curl the same end point to verify it can connect.

```
/app # curl -k -u elastic:password https://elastic.domain.something:9200
{
  "name" : "10.0.0.0",
  "cluster_name" : "cluster",
  "cluster_uuid" : "",
  "version" : {
    "number" : "7.4.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "",
    "build_date" : "2019-10-22T17:16:35.176724Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by moshe** [comment]
Can you try change verify_certs to ‘false’ instead of ‘“False”’?

**Comment by twigley** [comment]
Tried this with

``` "verify_certs": "false",```

and

```"verify_certs": false,```

but both return the same errors when accessing the root page

**Comment by moshe** [comment]
Seems like https://github.com/elastic/elasticsearch-py/issues/712 , can you try to add `"ca_certs": null` ?
if it's not working I will fix it during the weekend🙂

**Comment by twigley** [comment]
> Seems like [elastic/elasticsearch-py#712](https://github.com/elastic/elasticsearch-py/issues/712) , can you try to add `"ca_certs": null` ?
> if it's not working I will fix it during the weekend🙂

Tried that as well but get the same error.

**Comment by moshe** [comment]
Hey @twigley seems like a bug in elasticsearch client (pr fix [here](https://github.com/elastic/elasticsearch-py-async/pull/72)). In the meanwhile, you can delete the scheme parameter and add https and port on the hosts param. example:
```
{
  "params": {
    "hosts": [
      "https://localhost:9200"
    ],
    "http_auth": [
      "elastic",
      "PleaseChangeMe"
    ],
    "verify_certs": false
  },
  "name": "es-primary"
}
```

**Comment by twigley** [comment]
That's great. I'm up and running with the config above 👍

**Comment by moshe** [comment]
Great 👍
