### ISSUE TITLE
client.ping() encounter issue 

### ISSUE THREAD

**Issue by spursy** [moshe/elasticsearch-comrade#613]
File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/app/comrade/blueprints/cluster.py", line 36, in get_cluster_info
    await client.ping()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/elasticsearch_async/transport.py", line 150, in main_loop
    method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.7/site-packages/elasticsearch_async/connection.py", line 115, in perform_request
    yield from response.release()

**Comment by eric-engberg** [comment]
Here is the full stdout.

> /usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.26.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[2020-11-19 13:47:22 -0600] [8296] [INFO] Goin' Fast @ http://0.0.0.0:8000
[2020-11-19 13:47:22 -0600] [8296] [INFO] Starting worker [8296]
/home/eric/.local/lib/python3.6/site-packages/comrade/static/index.html
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/  200 2472
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/static/css/app.5d292c8a.css  304 0
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/static/css/chunk-vendors.f07fc4cd.css  304 0
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/static/js/app.2a698f05.js  304 0
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/static/js/chunk-vendors.c86c4216.js  304 0
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/static/css/snapshots.9593f1fa.css  304 0
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/static/js/snapshots.e089e908.js  304 0
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/api/v1/clients  200 23
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/static/fonts/MaterialIcons-Regular.0509ab09.woff2  304 0
[2020-11-19 13:47:26 -0600] [8296] [ERROR] 'noop' object is not iterable
Traceback (most recent call last):
  File "/home/eric/.local/lib/python3.6/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 129, in throw
    return self.gen.throw(type, value, traceback)
  File "/home/eric/.local/lib/python3.6/site-packages/comrade/blueprints/cluster.py", line 36, in get_cluster_info
    await client.ping()
  File "/home/eric/.local/lib/python3.6/site-packages/elasticsearch_async/transport.py", line 150, in main_loop
    method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/eric/.local/lib/python3.6/site-packages/elasticsearch_async/connection.py", line 115, in perform_request
    yield from response.release()
TypeError: 'noop' object is not iterable
[2020-11-19 13:47:26 -0600] - (sanic.access)[INFO][127.0.0.1:59958]: GET http://localhost:8000/api/v1/cluster/info/es-primary  200 899
[2020-11-19 13:47:31 -0600] [8296] [DEBUG] KeepAlive Timeout. Closing connection.
